// This file was generated automatically by Mendix Studio Pro when the
// "ConnectBroker" Java action is created with a single parameter of type
// "BrokerConfiguration" (entity) and a String return type. Everything
// outside the BEGIN/END USER CODE markers is regenerated by Studio Pro on
// every save; only the code between the markers is preserved. It is
// reproduced here in full for reference / offline review.
package amqpconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import com.solace.mendix.amqp.BrokerConfig;
import com.solace.mendix.amqp.BrokerConnector;
import com.solace.mendix.amqp.BrokerConnectorFactory;
import amqpconnector.impl.BrokerConfigMapper;
import amqpconnector.impl.ConnectionRegistry;

/**
 * Opens a connection to whichever broker is described by the given
 * BrokerConfiguration object and returns an opaque connection id. Pass that
 * id to SendMessage / StartListening / StopListening / DisconnectBroker.
 */
public class ConnectBroker extends CustomJavaAction<java.lang.String>
{
	private amqpconnector.proxies.BrokerConfiguration brokerConfiguration;

	public ConnectBroker(IContext context, amqpconnector.proxies.BrokerConfiguration brokerConfiguration)
	{
		super(context);
		this.brokerConfiguration = brokerConfiguration;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		BrokerConfig config = BrokerConfigMapper.from(this.brokerConfiguration);
		BrokerConnector connector = BrokerConnectorFactory.create(config);
		connector.connect();
		return ConnectionRegistry.register(connector);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConnectBroker";
	}
}
