// Generated by Studio Pro for a Java action with one String parameter
// ("ConnectionId") and a Boolean return type. See ConnectBroker.java for
// notes on the generated-vs-user-code split.
package amqpconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import com.solace.mendix.amqp.BrokerConnector;
import amqpconnector.impl.ConnectionRegistry;

/** Closes the connection identified by ConnectionId (as returned by ConnectBroker) and frees its resources. */
public class DisconnectBroker extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String connectionId;

	public DisconnectBroker(IContext context, java.lang.String connectionId)
	{
		super(context);
		this.connectionId = connectionId;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		BrokerConnector connector = ConnectionRegistry.remove(this.connectionId);
		if (connector == null) {
			return false;
		}
		connector.disconnect();
		return true;
		// END USER CODE
	}

	@java.lang.Override
	public java.lang.String toString()
	{
		return "DisconnectBroker";
	}
}
