// Generated by Studio Pro for a Java action with one String parameter
// ("ConnectionId") and a Boolean return type.
package amqpconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import com.solace.mendix.amqp.BrokerConnector;
import amqpconnector.impl.ConnectionRegistry;

/** Returns whether ConnectionId currently refers to a live, connected broker connection. */
public class IsConnected extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String connectionId;

	public IsConnected(IContext context, java.lang.String connectionId)
	{
		super(context);
		this.connectionId = connectionId;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		BrokerConnector connector = ConnectionRegistry.get(this.connectionId);
		return connector != null && connector.isConnected();
		// END USER CODE
	}

	@java.lang.Override
	public java.lang.String toString()
	{
		return "IsConnected";
	}
}
