// Generated by Studio Pro for a Java action with parameters ConnectionId
// (String), DestinationName (String), DestinationType (enumeration
// AMQPConnector.DestinationType), Payload (String) and a Boolean return
// type. See ConnectBroker.java for notes on the generated-vs-user-code split.
package amqpconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import com.solace.mendix.amqp.BrokerConnector;
import com.solace.mendix.amqp.BrokerConnectorException;
import com.solace.mendix.amqp.Destination;
import amqpconnector.impl.ConnectionRegistry;
import amqpconnector.impl.DestinationMapper;

/** Publishes Payload to the given queue or topic over the connection identified by ConnectionId. */
public class SendMessage extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String connectionId;
	private java.lang.String destinationName;
	private amqpconnector.proxies.ENUM_DestinationType destinationType;
	private java.lang.String payload;

	public SendMessage(IContext context, java.lang.String connectionId, java.lang.String destinationName,
			amqpconnector.proxies.ENUM_DestinationType destinationType, java.lang.String payload)
	{
		super(context);
		this.connectionId = connectionId;
		this.destinationName = destinationName;
		this.destinationType = destinationType;
		this.payload = payload;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		BrokerConnector connector = ConnectionRegistry.get(this.connectionId);
		if (connector == null || !connector.isConnected()) {
			throw new BrokerConnectorException(
					"No active connection for ConnectionId '" + this.connectionId + "'. Call ConnectBroker first.");
		}
		Destination destination = DestinationMapper.toDestination(this.destinationName, this.destinationType);
		connector.send(destination, this.payload);
		return true;
		// END USER CODE
	}

	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendMessage";
	}
}
