// Generated by Studio Pro for a Java action with parameters ConnectionId
// (String), DestinationName (String), DestinationType (enumeration
// AMQPConnector.DestinationType), OnMessageMicroflow (String, e.g.
// "AMQPConnector.SUB_OnMessageReceived") and a Boolean return type.
// See ConnectBroker.java for notes on the generated-vs-user-code split.
package amqpconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import com.solace.mendix.amqp.*;
import amqpconnector.impl.ConnectionRegistry;
import amqpconnector.impl.DestinationMapper;

/**
 * Registers an asynchronous listener on a queue or topic. Every message
 * received calls the microflow named in OnMessageMicroflow with the
 * parameters ConnectionId (String), DestinationName (String), MessageId
 * (String) and Payload (String) &mdash; create that microflow first with
 * matching parameter names/types (see README-STUDIO-PRO-SETUP.md) before
 * wiring this action to it.
 */
public class StartListening extends CustomJavaAction<java.lang.Boolean>
{
	private static final ILogNode LOG = Core.getLogger("AMQPConnector");

	private java.lang.String connectionId;
	private java.lang.String destinationName;
	private amqpconnector.proxies.ENUM_DestinationType destinationType;
	private java.lang.String onMessageMicroflow;

	public StartListening(IContext context, java.lang.String connectionId, java.lang.String destinationName,
			amqpconnector.proxies.ENUM_DestinationType destinationType, java.lang.String onMessageMicroflow)
	{
		super(context);
		this.connectionId = connectionId;
		this.destinationName = destinationName;
		this.destinationType = destinationType;
		this.onMessageMicroflow = onMessageMicroflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		BrokerConnector connector = ConnectionRegistry.get(this.connectionId);
		if (connector == null || !connector.isConnected()) {
			throw new BrokerConnectorException(
					"No active connection for ConnectionId '" + this.connectionId + "'. Call ConnectBroker first.");
		}
		Destination destination = DestinationMapper.toDestination(this.destinationName, this.destinationType);
		final String microflowName = this.onMessageMicroflow;
		final String connectionIdCopy = this.connectionId;

		Subscription subscription = connector.subscribe(destination, inbound -> {
			try {
				// JMS delivery happens on a broker-client thread with no
				// Mendix request context, so a fresh system context is used
				// for the callback microflow.
				IContext callbackContext = Core.createSystemContext();
				Core.microflowCall(microflowName)
						.withParam("ConnectionId", connectionIdCopy)
						.withParam("DestinationName", inbound.getDestinationName())
						.withParam("MessageId", inbound.getMessageId())
						.withParam("Payload", inbound.getPayload())
						.execute(callbackContext);
			} catch (Exception e) {
				LOG.error("Error invoking callback microflow '" + microflowName + "' for message from "
						+ inbound.getDestinationName() + ": " + e.getMessage(), e);
			}
		});

		ConnectionRegistry.registerSubscription(this.connectionId, this.destinationName, subscription);
		return true;
		// END USER CODE
	}

	@java.lang.Override
	public java.lang.String toString()
	{
		return "StartListening";
	}
}
