// Generated by Studio Pro for a Java action with parameters ConnectionId
// (String), DestinationName (String) and a Boolean return type.
package amqpconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import com.solace.mendix.amqp.Subscription;
import amqpconnector.impl.ConnectionRegistry;

/** Cancels the listener started by StartListening for the given ConnectionId + DestinationName pair. */
public class StopListening extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String connectionId;
	private java.lang.String destinationName;

	public StopListening(IContext context, java.lang.String connectionId, java.lang.String destinationName)
	{
		super(context);
		this.connectionId = connectionId;
		this.destinationName = destinationName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Subscription subscription = ConnectionRegistry.removeSubscription(this.connectionId, this.destinationName);
		if (subscription == null) {
			return false;
		}
		subscription.close();
		return true;
		// END USER CODE
	}

	@java.lang.Override
	public java.lang.String toString()
	{
		return "StopListening";
	}
}
